
version: '3.1'

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    environment:
      PG_PASSWORD: $POSTGRES_PASSWORD
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgresql:/var/lib/postgresql
  django:
    container_name: djangoproject
    build:
      context: .
    command: python django_app.py runserver 0.0.0.0:8000 --noreload
    ports:
      - 8000:8000
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    volumes:
      - .:/src
    networks:
      - botnet
    restart: always
    environment:
      TZ: Europe/Moscow
    env_file:
      - ".env"
    depends_on:
      - db
      - django


networks:
  botnet:
    driver: bridge