# Generated by Django 3.1.6 on 2021-02-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usersmanage.document', verbose_name='Файл'),
            preserve_default=False,
        ),
    ]
