# Generated by Django 3.1.6 on 2021-02-21 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0004_auto_20210220_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('file_id', models.CharField(max_length=200, verbose_name='Файл file_id')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.document', verbose_name='Файл'),
        ),
    ]
