# Generated by Django 3.1.6 on 2021-02-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0006_auto_20210221_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category_name',
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
