# Generated by Django 3.1.6 on 2021-02-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0007_auto_20210221_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(upload_to='documents', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(upload_to='images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.item', verbose_name='Идентификатор товара'),
        ),
    ]
